export TERM=xterm-256colo
export PS1="\[\e[31m\]bd-python-docker\[\e[m\] \[\e[33m\]\w\[\e[m\] > "
export TERM=xterm-256color
alias grep="grep --color=auto"
alias ls="ls --color=auto"

echo -e "\e[1;31m"
cat << BD
   ___  ______   __   ___  ___ _________
  / _ )/ __/ /  / /  / _ \/ _ /_  __/ _ |
 / _  / _// /__/ /__/ // / __ |/ / / __ |
/____/___/____/____/____/_/ |_/_/ /_/ |_|
BD
echo -e "\e[0;33m"

echo -e "\e[m"